name: Build and Release

on:
  push:
    branches: [ main ]

jobs:
  create-release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')  # Solo crea un release si se empujó un tag
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ 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 }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
          
  build:
    needs: create-release
    if: startsWith(github.ref, 'refs/tags/')  # Solo construye si se empujó un tag
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
        shell: bash

      - name: Build and publish
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run publish
        shell: bash

  build-on-push:
    runs-on: windows-latest
    if: "!startsWith(github.ref, 'refs/tags/')"
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build only (no publish)
        run: npm run build
